### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by matteocontrini** [Neetuj/python-wns#1]
Can you give a simple example of how to use it?

Thanks

**Comment by matteocontrini** [comment]
Ok, managed to get it working looking at the tests. Maybe I'll write something in the wiki.
The module is good :)

**Comment by Neetuj** [comment]
Hi I will add an example soon. 
Thanks!

**Comment by Neetuj** [comment]
Toast notification example added. Will add tile e.t.c too
